# Generated by Django 4.1.7 on 2023-03-19 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkloop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimpression',
            name='anonymous_views',
            field=models.PositiveIntegerField(db_column='anonymous_view', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profileimpression',
            name='viewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileimpression',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
