# Generated by Django 4.1.7 on 2023-03-20 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkloop_app', '0002_alter_profileimpression_anonymous_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profileimpression',
            name='anonymous_views',
        ),
        migrations.RemoveField(
            model_name='videoimpression',
            name='anonymous_views',
        ),
        migrations.AddField(
            model_name='message',
            name='message_text',
            field=models.TextField(db_column='message_text', default='', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
