# Generated by Django 4.1.7 on 2023-04-10 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0007_video_title_videoimpression_impression_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(db_column='headline', default='', max_length=32, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
