# Generated by Django 4.1.7 on 2023-04-14 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0010_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, db_column='about', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(db_column='headline', default='', max_length=64, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
