# Generated by Django 4.1.7 on 2023-04-14 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0011_alter_profile_about_alter_profile_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, db_column='location', default='', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
