# Generated by Django 4.1.7 on 2023-04-14 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0012_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, db_column='headline', default='', max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
