# Generated by Django 4.1.7 on 2023-04-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0013_remove_profile_website_alter_profile_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
