# Generated by Django 4.1.7 on 2023-04-15 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0014_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, db_column='about', max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
