# Generated by Django 4.1.7 on 2023-04-24 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0022_alter_education_education_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education_description',
            field=models.TextField(db_column='education_description', default='', max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_description',
            field=models.TextField(db_column='experience_description', max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
