# Generated by Django 4.1.7 on 2023-04-24 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0023_alter_education_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_description',
            field=models.TextField(db_column='experience_description', max_length=300, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
