# Generated by Django 4.1.7 on 2023-05-02 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0029_video_video_id_name_alter_videolike_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(db_column='title', max_length=64, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
