# Generated by Django 4.1.7 on 2023-05-04 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0030_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(db_column='description', max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
