# Generated by Django 4.1.7 on 2023-05-08 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkloop_app', '0031_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(db_column='topic', max_length=64, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id_name',
            field=models.CharField(default='', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=128, verbose_name='video_url'),
        ),
    ]
