# Generated by Django 4.1.7 on 2023-05-09 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkloop_app', '0033_alter_usersearch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimpression',
            name='viewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='linkloop_app.profile'),
        ),
        migrations.AlterField(
            model_name='profileimpression',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_impressions', to=settings.AUTH_USER_MODEL),
        ),
    ]
