export const URL = "http://127.0.0.1:8000/"
// export const URL = "http://ec2-18-212-171-140.compute-1.amazonaws.com/";
export const APIV1 = "api/v1/"
export const AUTH = "auth/"
export const PROFILE = "profile/"
export const QUALS = "quals/"
export const VIDEOS = "videos/"
export const SEARCH = "search/"
export const MAIN = "main/"
export const USERS = "users/";
